---
# tasks file for db_config

  - name: create mysql db
    mysql_db:
      name: "{{ wp_db_name }}"
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock
    when:  ansible_facts['os_family'] == "Debian"

  - name: create db user
    mysql_user:
      name: "{{ wp_db_user }}"
      host: localhost
      password: "{{ wp_db_password }}"
      priv: "{{ wp_db_name }}.*:ALL"
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock
    notify: Start MYSQL
    when:  ansible_facts['os_family'] == "Debian"

  - name: copy sample config
    copy:
      src: /srv/www/wordpress/wp-config-sample.php
      dest: /srv/www/wordpress/wp-config.php
      remote_src: yes
      owner: www-data
      group: www-data
      mode: '0644'
    become: yes
    when:  ansible_facts['os_family'] == "Debian"

  - name: set db-name
    lineinfile:
      path: /srv/www/wordpress/wp-config.php
      regexp: "define\\(\\s*'DB_NAME'.*"
      line: "define('DB_NAME', '{{ wp_db_name }}');"
      owner: www-data
      group: www-data
      mode: '0644'
    become: yes
    when:  ansible_facts['os_family'] == "Debian"

  - name: set db-user
    lineinfile:
      path: /srv/www/wordpress/wp-config.php
      regexp: "define\\(\\s*'DB_USER'.*"
      line: "define('DB_USER', '{{ wp_db_user }}');"
      owner: www-data
      group: www-data
      mode: '0644'
    become: yes
    when:  ansible_facts['os_family'] == "Debian"

  - name: set db-passwd
    lineinfile:
      path: /srv/www/wordpress/wp-config.php
      regexp: "define\\(\\s*'DB_PASSWORD'.*"
      line: "define('DB_PASSWORD', '{{ wp_db_password }}');"
      owner: www-data
      group: www-data
      mode: '0644'
    become: yes
    when:  ansible_facts['os_family'] == "Debian"

  - name: Ensure mariadb is running
    service:
      name: mariadb
      state: started
      enabled: true
    when:  ansible_facts['os_family'] == "RedHat"

  - name: Set MariaDB root password (socket auth)
    mysql_user:
      login_unix_socket: "{{ mariadb_socket }}"
      user: root
      password: "{{ mysql_root_password }}"
      host: "%"
      state: present
    when:  ansible_facts['os_family'] == "RedHat"

  - name: Remove anonymous users
    mysql_user:
      login_unix_socket: "{{ mariadb_socket }}"
      name: ''
      host_all: true
      state: absent
    when:  ansible_facts['os_family'] == "RedHat"

  - name: Remove test database
    mysql_db:
      login_unix_socket: "{{ mariadb_socket }}"
      name: test
      state: absent
    when:  ansible_facts['os_family'] == "RedHat"

  - name: Creating DB
    mysql_db:
      login_unix_socket: "{{ mariadb_socket }}"
      name: "{{ wp_db_name }}"
      state: present
    when:  ansible_facts['os_family'] == "RedHat"

  - name: Create DB user
    mysql_user:
      login_unix_socket: "{{ mariadb_socket }}"
      name: "{{ wp_db_user }}"
      host: localhost
      password: "{{ wp_db_password }}"
      priv: "{{ wp_db_name }}.*:ALL"
      state: present
    when:  ansible_facts['os_family'] == "RedHat"











