---
# vars file for db_config

  ansible_mysql_login_user: root
  wp_db_name: wordpress
  wp_db_user: wordpress
  wp_db_password: "123456789"
  mysql_root_password: "123456789"
  mariadb_socket: /var/lib/mysql/mysql.sock
