---
# vars file for install_dependecies
pack_deb:
  - apache2
  - ghostscript
  - libapache2-mod-php
  - mysql-server
  - php
  - php-bcmath
  - php-curl
  - php-imagick
  - php-intl
  - php-json
  - php-mbstring
  - php-mysql
  - php-xml
  - php-zip
  - python3-pymysql

pack_rh:
  - httpd
  - mariadb
  - mariadb-server
  - php-gd
  - php-soap
  - php-intl
  - php-mysqlnd
  - php-pdo
  - php-pecl-zip
  - php-fpm
  - php-opcache
  - php-curl
  - php-zip
  - php-xmlrpc
  - wget
  - python3-PyMySQL
  - policycoreutils-python-utils
  - php-json
