---
# tasks file for workdir
  
  - name: creating /srv/www
    file:
      path: /srv/www
      state: directory
      owner: www-data
      group: www-data
      mode: "0755"
    when:  ansible_facts['os_family'] == "Debian"
     
  - name: create dir
    file:
      path: /var/www/html
      state: directory
      mode: "0755"
    when:  ansible_facts['os_family'] == "RedHat"
